### ISSUE TITLE
Does not install properly on all machines/installations

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#22]
2017-09-24 09:50:28,187 - Loading NECN Hydro Succession extension ...
2017-09-24 09:50:28,195 - Error while loading the plug-in:
  Cannot get the data type that implements the plug-in:
    Data type:  Landis.Extension.Succession.NECNhydro.PlugIn,Landis.Extension.Succession.NECNhydro
    Error:      No data type with that name is installed.

**Comment by rmscheller** [comment]
I just tested it with Core v6.1.  Same problem, so that's good?

**Comment by rmscheller** [comment]
Austen,
I did a rebuild and I'm still getting this error:
2017-10-08 12:09:28,362 - Loading NECN_Hydro Succession extension ...
2017-10-08 12:09:28,370 - Error while loading the plug-in:
  Cannot get the data type that implements the plug-in:
    Data type:  Landis.Extension.Succession.NECN_Hydro.PlugIn,Landis.Extension.Succession.NECN_Hydro
    Error:      No data type with that name is installed.

**Comment by mslucash** [comment]
I just downloaded the version 0.7 and it downloads, but..

1) it triggers an error in the input file.  See below.
2) If I fix that error, then I get a parsing error below.

I can't check to make sure my input files are correct, because the examples have problems 1 and 2 too.

Problem 1)
2017-10-16 08:23:47,897 -    Registering Data:  Succession.FineFuels.
2017-10-16 08:23:47,955 - Error at line 29 of file "NECN_H_succession_landscape.txt":
  Found the name "InitialDeadWoodSoilMapName" but expected "InitialDeadCoarseRootsMapName"

Problem 2)
2017-10-16 08:21:28,496 - Initializing NECN_Hydro Succession ...
2017-10-16 08:21:28,533 - Internal error occurred within the program:
2017-10-16 08:21:28,533 -   Object reference not set to an instance of an object.
2017-10-16 08:21:28,533 - 
2017-10-16 08:21:28,533 - Stack trace:
2017-10-16 08:21:28,537 -    at Edu.Wisc.Forest.Flel.Util.InputValue`1.op_Implicit(InputValue`1 inputValue)
   at Landis.Library.Climate.InputParametersParser.Parse()
   at Edu.Wisc.Forest.Flel.Util.TextParser`1.Parse(LineReader reader)

**Comment by mslucash** [comment]
OK, so I tested it with Alec's test landscape and it runs fine.  Maybe something changed in the input files or something.  More soon.

**Comment by mslucash** [comment]
OK, it needed this extra text in the climate input file to run.
UsingFireClimate   no

Runs fine now!

**Comment by rmscheller** [comment]
Ah, shoot, I thought I had that as an optional variable.
