### ISSUE TITLE
When reading in maps, the error message doesn't tell you which map is the problem

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#36]
If one of the maps isn't in the correct format (e.g. float), then it triggers an error but doesn't tell you WHICH map.  There are now 18 maps in the NECN input file so it takes a while to track down the source of the error.

**Comment by rmscheller** [comment]
Could you post an example log file?

**Comment by mslucash** [comment]
In this case, the error was in this map:
InitialSOM3CMapName		singlecell_2382.img <<2382

But I had to systematically test each map to find out it was the 16th map causing the problem.

Melissa

2018-03-30 07:50:17,914 - LANDIS-II 6.2 (official release)
2018-03-30 07:50:17,954 - 
2018-03-30 07:50:18,164 - Loading scenario from file "scenario_ML.txt" ...
2018-03-30 07:50:18,232 - Initialized random number generator with seed = 2,147,616,581
2018-03-30 07:50:18,232 - Loading species data from file "species_ML.txt" ...
2018-03-30 07:50:18,256 - Loading ecoregions from file "ecoregions.txt" ...
2018-03-30 07:50:18,275 - Initializing landscape from ecoregions map "singlecell_3.img" ...
2018-03-30 07:50:18,300 - Cell length = 100 m, cell area = 1 ha
2018-03-30 07:50:18,302 - Map dimensions: 1 row by 1 column = 1 cell
2018-03-30 07:50:18,310 - Sites: 1 active (100.0 %), 0 inactive (0.0 %)
2018-03-30 07:50:18,320 - Loading NECN_Hydro Succession extension ...
2018-03-30 07:50:18,344 -    Registering Data:  Succession.LeafBiomassCohorts.
2018-03-30 07:50:18,345 -    Registering Data:  Succession.AgeCohorts.
2018-03-30 07:50:18,345 -    Registering Data:  Succession.BiomassCohorts.
2018-03-30 07:50:18,345 -    Registering Data:  Succession.FineFuels.
2018-03-30 07:50:18,390 -    Begin parsing FUNCTIONAL GROUP table.
2018-03-30 07:50:18,394 -    Begin reading FIRE REDUCTION parameters.
2018-03-30 07:50:18,395 -    Begin reading HARVEST REDUCTION parameters.
2018-03-30 07:50:18,401 - Initializing NECN_Hydro Succession ...
2018-03-30 07:50:18,443 -    Loading weather data ...
2018-03-30 07:50:18,846 - Internal error occurred within the program:
2018-03-30 07:50:18,846 -   Raster band is not byte, short, int, float, double
2018-03-30 07:50:18,847 - 
2018-03-30 07:50:18,847 - Stack trace:
2018-03-30 07:50:18,869 -    at Landis.RasterIO.Gdal.GdalInputRaster`1.NewInputBand(Band gdalBand, PixelBand pixelBand)
   at Landis.RasterIO.Gdal.GdalInputRaster`1..ctor(String path)
   at Landis.RasterIO.Gdal.RasterFactory.OpenRaster[TPixel](String path)
   at Landis.Model.Landis.SpatialModeling.IRasterFactory.OpenRaster[TPixel](String path)
   at Landis.Extension.Succession.NECN_Hydro.Util.MakeDoubleMap(String path) in c:\Users\lucash\Documents\LANDIS_Code\NECN_CapacityLimit_Branch\Extension-NECN-Hydro-Succession\src\utility\Util.cs:line 523
   at Landis.Extension.Succession.NECN_Hydro.Util.ReadSoilCNMaps(String path, String path2, String path3, String path4, String path5, String path6, String path7, String path8) in c:\Users\lucash\Documents\LANDIS_Code\NECN_CapacityLimit_Branch\Extension-NECN-Hydro-Succession\src\utility\Util.cs:line 476
   at Landis.Extension.Succession.NECN_Hydro.PlugIn.Initialize() in c:\Users\lucash\Documents\LANDIS_Code\NECN_CapacityLimit_Branch\Extension-NECN-Hydro-Succession\src\PlugIn.cs:line 113
   at Landis.Model.Run(String scenarioPath, IUserInterface ui)
   at Landis.App.Main(String[] args)

**Comment by rmscheller** [comment]
Done.  See installer 0.9.71
